services:
  # -------------------------------------------------------------------------------- #
  # backend service with nitro.unjs                                                  #
  # -------------------------------------------------------------------------------- #
  backend:
    container_name: backend
    build: backend
    ports:
      - 3000:3000
    networks:
      - matcha_network
    volumes:
      - ./backend:/usr/src/app
    env_file: .env

  # -------------------------------------------------------------------------------- #
  # frontend service with Vite-React                                                 #
  # -------------------------------------------------------------------------------- #
  frontend:
    container_name: frontend
    build: frontend
    ports:
      - 5173:5173
    networks:
      - matcha_network
    volumes:
      - ./frontend:/usr/src/app

  # -------------------------------------------------------------------------------- #
  # postgresql database                                                              #
  # -------------------------------------------------------------------------------- # 
  database:
    image: postgres:16.4
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - matcha_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env

  pg-admin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 5050:80
    networks:
      - matcha_network
    env_file: .env

# -------------------------------------------------------------------------------- #
# networks                                                                         #
# -------------------------------------------------------------------------------- #
networks:
  matcha_network:

# -------------------------------------------------------------------------------- #
# volumes                                                                          #
# -------------------------------------------------------------------------------- #
volumes:
  postgres-data:
    name: postgres-data

